//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Bolnica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IS_Bolnica.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj smenu.
        /// </summary>
        public static string AddShiftButton {
            get {
                return ResourceManager.GetString("AddShiftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj slobodne dane.
        /// </summary>
        public static string AddVacationButton {
            get {
                return ResourceManager.GetString("AddVacationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj slobodne dane.
        /// </summary>
        public static string AddVacationLabel {
            get {
                return ResourceManager.GetString("AddVacationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa:.
        /// </summary>
        public static string AdressLabel {
            get {
                return ResourceManager.GetString("AdressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi alergeni:.
        /// </summary>
        public static string AllAllergensLabel {
            get {
                return ResourceManager.GetString("AllAllergensLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergeni:.
        /// </summary>
        public static string AllergenLabel {
            get {
                return ResourceManager.GetString("AllergenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALERGENI.
        /// </summary>
        public static string AllergensLabel {
            get {
                return ResourceManager.GetString("AllergensLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOKIRANI PACIJENTI.
        /// </summary>
        public static string BlockedButton {
            get {
                return ResourceManager.GetString("BlockedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum:.
        /// </summary>
        public static string ChooseDateLabel {
            get {
                return ResourceManager.GetString("ChooseDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite doktora:.
        /// </summary>
        public static string ChooseDocLabel {
            get {
                return ResourceManager.GetString("ChooseDocLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite trajanje (min):.
        /// </summary>
        public static string ChooseDurLabel {
            get {
                return ResourceManager.GetString("ChooseDurLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite trajanje:.
        /// </summary>
        public static string ChooseDurOpLabel {
            get {
                return ResourceManager.GetString("ChooseDurOpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite pregled:.
        /// </summary>
        public static string ChooseEx {
            get {
                return ResourceManager.GetString("ChooseEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik:.
        /// </summary>
        public static string ChooseLanguageLabel {
            get {
                return ResourceManager.GetString("ChooseLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite režim:.
        /// </summary>
        public static string ChooseModeLabel {
            get {
                return ResourceManager.GetString("ChooseModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite operaciju:.
        /// </summary>
        public static string ChooseOp {
            get {
                return ResourceManager.GetString("ChooseOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite smenu:.
        /// </summary>
        public static string ChooseShiftLabel {
            get {
                return ResourceManager.GetString("ChooseShiftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite vreme:.
        /// </summary>
        public static string ChooseTimeLabel {
            get {
                return ResourceManager.GetString("ChooseTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad:.
        /// </summary>
        public static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj.
        /// </summary>
        public static string ContentHeader {
            get {
                return ResourceManager.GetString("ContentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj:.
        /// </summary>
        public static string ContentLabel {
            get {
                return ResourceManager.GetString("ContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj obaveštenja:.
        /// </summary>
        public static string ContLabel {
            get {
                return ResourceManager.GetString("ContLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država:.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj guest nalog.
        /// </summary>
        public static string CreateGuestLabel {
            get {
                return ResourceManager.GetString("CreateGuestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj obaveštenje.
        /// </summary>
        public static string CreateNotificationLabel {
            get {
                return ResourceManager.GetString("CreateNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj izveštaj.
        /// </summary>
        public static string CreateReportButton {
            get {
                return ResourceManager.GetString("CreateReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja:.
        /// </summary>
        public static string DateBirthLabel {
            get {
                return ResourceManager.GetString("DateBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum od:.
        /// </summary>
        public static string DateFromLabel {
            get {
                return ResourceManager.GetString("DateFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vreme.
        /// </summary>
        public static string DateHeader {
            get {
                return ResourceManager.GetString("DateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum do:.
        /// </summary>
        public static string DateToLabel {
            get {
                return ResourceManager.GetString("DateToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG doktora:.
        /// </summary>
        public static string DocJMBGLabel {
            get {
                return ResourceManager.GetString("DocJMBGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite doktora:.
        /// </summary>
        public static string DocLabel {
            get {
                return ResourceManager.GetString("DocLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor.
        /// </summary>
        public static string DoctorHeader {
            get {
                return ResourceManager.GetString("DoctorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOKTORI.
        /// </summary>
        public static string DoctorsButton {
            get {
                return ResourceManager.GetString("DoctorsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena pregleda.
        /// </summary>
        public static string EditExLabel {
            get {
                return ResourceManager.GetString("EditExLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni obaveštenje.
        /// </summary>
        public static string EditNotificationLabel {
            get {
                return ResourceManager.GetString("EditNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena operacije.
        /// </summary>
        public static string EditOpLabel {
            get {
                return ResourceManager.GetString("EditOpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena pacijenta.
        /// </summary>
        public static string EditPatientLabel {
            get {
                return ResourceManager.GetString("EditPatientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREGLEDI.
        /// </summary>
        public static string ExaminationButton {
            get {
                return ResourceManager.GetString("ExaminationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTOJEĆI.
        /// </summary>
        public static string ExistableLabel {
            get {
                return ResourceManager.GetString("ExistableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol:.
        /// </summary>
        public static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUEST NALOZI.
        /// </summary>
        public static string GuestButton {
            get {
                return ResourceManager.GetString("GuestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi guest nalog.
        /// </summary>
        public static string GuestCreateButton {
            get {
                return ResourceManager.GetString("GuestCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUEST.
        /// </summary>
        public static string GuestLab {
            get {
                return ResourceManager.GetString("GuestLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis povrede.
        /// </summary>
        public static string InjuryHeader {
            get {
                return ResourceManager.GetString("InjuryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis povrede:.
        /// </summary>
        public static string InjuryLabel {
            get {
                return ResourceManager.GetString("InjuryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG:.
        /// </summary>
        public static string jmbg {
            get {
                return ResourceManager.GetString("jmbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG.
        /// </summary>
        public static string JMBGHeader {
            get {
                return ResourceManager.GetString("JMBGHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG pacijenta:.
        /// </summary>
        public static string JMBGLabel {
            get {
                return ResourceManager.GetString("JMBGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZDRAVO KORPORACIJA.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBAVEŠTENJA.
        /// </summary>
        public static string NotificationsButton {
            get {
                return ResourceManager.GetString("NotificationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov:.
        /// </summary>
        public static string NotifTitleLabel {
            get {
                return ResourceManager.GetString("NotifTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciona sala:.
        /// </summary>
        public static string OpRoomLabel {
            get {
                return ResourceManager.GetString("OpRoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcije.
        /// </summary>
        public static string OptionLabel {
            get {
                return ResourceManager.GetString("OptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPCIJE.
        /// </summary>
        public static string OptionsButton {
            get {
                return ResourceManager.GetString("OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergeni pacijenta:.
        /// </summary>
        public static string PatientsAllergensLabel {
            get {
                return ResourceManager.GetString("PatientsAllergensLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACIJENTI.
        /// </summary>
        public static string PatientsButton {
            get {
                return ResourceManager.GetString("PatientsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil pacijenta.
        /// </summary>
        public static string PatientsProfile {
            get {
                return ResourceManager.GetString("PatientsProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG pacijenta.
        /// </summary>
        public static string PatJMBGHeader {
            get {
                return ResourceManager.GetString("PatJMBGHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFIL.
        /// </summary>
        public static string ProfileButton {
            get {
                return ResourceManager.GetString("ProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite da napravite guest nalog?.
        /// </summary>
        public static string questionLab {
            get {
                return ResourceManager.GetString("questionLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovanje pacijenta.
        /// </summary>
        public static string RegisterPatientLabel {
            get {
                return ResourceManager.GetString("RegisterPatientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbaci.
        /// </summary>
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IZVEŠTAJ.
        /// </summary>
        public static string ReportButton {
            get {
                return ResourceManager.GetString("ReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma za kreiranje izveštaja.
        /// </summary>
        public static string ReportForm {
            get {
                return ResourceManager.GetString("ReportForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soba.
        /// </summary>
        public static string RoomHeader {
            get {
                return ResourceManager.GetString("RoomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite sobu:.
        /// </summary>
        public static string RoomLabel {
            get {
                return ResourceManager.GetString("RoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži pregled.
        /// </summary>
        public static string ScheduleEx {
            get {
                return ResourceManager.GetString("ScheduleEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži operaciju.
        /// </summary>
        public static string ScheduleOp {
            get {
                return ResourceManager.GetString("ScheduleOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakažite operaciju.
        /// </summary>
        public static string ScheduleOpLabel {
            get {
                return ResourceManager.GetString("ScheduleOpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakažite pregled.
        /// </summary>
        public static string SchedulingExLabel {
            get {
                return ResourceManager.GetString("SchedulingExLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži opcije termina.
        /// </summary>
        public static string ShowOptionsButton {
            get {
                return ResourceManager.GetString("ShowOptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalizacija doktora:.
        /// </summary>
        public static string SpecializationLabel {
            get {
                return ResourceManager.GetString("SpecializationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERACIJE.
        /// </summary>
        public static string SurgeryButton {
            get {
                return ResourceManager.GetString("SurgeryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string SurnameHeader {
            get {
                return ResourceManager.GetString("SurnameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        public static string SurnameLabel {
            get {
                return ResourceManager.GetString("SurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemsko ime:.
        /// </summary>
        public static string SysNameLabel {
            get {
                return ResourceManager.GetString("SysNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemsko ime.
        /// </summary>
        public static string SystemNameHeader {
            get {
                return ResourceManager.GetString("SystemNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona:.
        /// </summary>
        public static string TelephoneLabel {
            get {
                return ResourceManager.GetString("TelephoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov obaveštenja:.
        /// </summary>
        public static string TitLabel {
            get {
                return ResourceManager.GetString("TitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov.
        /// </summary>
        public static string TitleHeader {
            get {
                return ResourceManager.GetString("TitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odblokiraj pacijenta.
        /// </summary>
        public static string UnblockButton {
            get {
                return ResourceManager.GetString("UnblockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAKAŽI HITAN PREGLED.
        /// </summary>
        public static string UrgentExButton {
            get {
                return ResourceManager.GetString("UrgentExButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAKAŽI HITNU OPERACIJU.
        /// </summary>
        public static string UrgentOpButton {
            get {
                return ResourceManager.GetString("UrgentOpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži hitan pregled.
        /// </summary>
        public static string UrgExLabel {
            get {
                return ResourceManager.GetString("UrgExLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži hitnu operaciju.
        /// </summary>
        public static string UrgOpLabel {
            get {
                return ResourceManager.GetString("UrgOpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik:.
        /// </summary>
        public static string UserLabel {
            get {
                return ResourceManager.GetString("UserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string UsernameHeader {
            get {
                return ResourceManager.GetString("UsernameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime:.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip korisnika.
        /// </summary>
        public static string UserTypeHeader {
            get {
                return ResourceManager.GetString("UserTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *tip korisnika.
        /// </summary>
        public static string UserTypeLab {
            get {
                return ResourceManager.GetString("UserTypeLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip korisnika:.
        /// </summary>
        public static string UserTypeLabel {
            get {
                return ResourceManager.GetString("UserTypeLabel", resourceCulture);
            }
        }
    }
}
