//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Bolnica.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IS_Bolnica.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string adresa {
            get {
                return ResourceManager.GetString("adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergeni.
        /// </summary>
        public static string alergeni {
            get {
                return ResourceManager.GetString("alergeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOKIRANI PACIJENTI.
        /// </summary>
        public static string blokirani_pacijenti {
            get {
                return ResourceManager.GetString("blokirani_pacijenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string broj_tel {
            get {
                return ResourceManager.GetString("broj_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string datum {
            get {
                return ResourceManager.GetString("datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        public static string datum_rodjenja {
            get {
                return ResourceManager.GetString("datum_rodjenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vreme.
        /// </summary>
        public static string datum_vreme {
            get {
                return ResourceManager.GetString("datum_vreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string dodaj {
            get {
                return ResourceManager.GetString("dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj slobodan dan/odmor.
        /// </summary>
        public static string dodaj_slobodan_dan {
            get {
                return ResourceManager.GetString("dodaj_slobodan_dan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj slobodne dane.
        /// </summary>
        public static string dodaj_slobodne_dane {
            get {
                return ResourceManager.GetString("dodaj_slobodne_dane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj smenu.
        /// </summary>
        public static string dodaj_smenu {
            get {
                return ResourceManager.GetString("dodaj_smenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor.
        /// </summary>
        public static string doktor {
            get {
                return ResourceManager.GetString("doktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOKTORI.
        /// </summary>
        public static string doktori {
            get {
                return ResourceManager.GetString("doktori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string drzava {
            get {
                return ResourceManager.GetString("drzava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string grad {
            get {
                return ResourceManager.GetString("grad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUEST.
        /// </summary>
        public static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUEST NALOZI.
        /// </summary>
        public static string guest_nalozi {
            get {
                return ResourceManager.GetString("guest_nalozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string ime {
            get {
                return ResourceManager.GetString("ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum.
        /// </summary>
        public static string izaberite_datum {
            get {
                return ResourceManager.GetString("izaberite_datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite doktora.
        /// </summary>
        public static string izaberite_doktora {
            get {
                return ResourceManager.GetString("izaberite_doktora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži operaciju.
        /// </summary>
        public static string izaberite_operaciju {
            get {
                return ResourceManager.GetString("izaberite_operaciju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite pregled.
        /// </summary>
        public static string izaberite_pregled {
            get {
                return ResourceManager.GetString("izaberite_pregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite smenu.
        /// </summary>
        public static string izaberite_smenu {
            get {
                return ResourceManager.GetString("izaberite_smenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite trajanje.
        /// </summary>
        public static string izaberite_trajanje {
            get {
                return ResourceManager.GetString("izaberite_trajanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite vreme.
        /// </summary>
        public static string izaberite_vreme {
            get {
                return ResourceManager.GetString("izaberite_vreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbaci.
        /// </summary>
        public static string izbaci {
            get {
                return ResourceManager.GetString("izbaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena operacije.
        /// </summary>
        public static string izmena_operacije {
            get {
                return ResourceManager.GetString("izmena_operacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena pregleda.
        /// </summary>
        public static string izmena_pregleda {
            get {
                return ResourceManager.GetString("izmena_pregleda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string izmeni {
            get {
                return ResourceManager.GetString("izmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IZVEŠTAJ.
        /// </summary>
        public static string izvestaj {
            get {
                return ResourceManager.GetString("izvestaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG doktora.
        /// </summary>
        public static string jmbg_doktora {
            get {
                return ResourceManager.GetString("jmbg_doktora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG pacijenta.
        /// </summary>
        public static string jmbg_pacijenta {
            get {
                return ResourceManager.GetString("jmbg_pacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string korisnicko_ime {
            get {
                return ResourceManager.GetString("korisnicko_ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG korisnika.
        /// </summary>
        public static string korisnik {
            get {
                return ResourceManager.GetString("korisnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj važenja godišnjeg.
        /// </summary>
        public static string kraj_vazenja_godisnjeg {
            get {
                return ResourceManager.GetString("kraj_vazenja_godisnjeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj važenja smene.
        /// </summary>
        public static string kraj_vazenja_smene {
            get {
                return ResourceManager.GetString("kraj_vazenja_smene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj nalog.
        /// </summary>
        public static string kreiraj_nalog {
            get {
                return ResourceManager.GetString("kreiraj_nalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiranje guest naloga.
        /// </summary>
        public static string kreiranje_guest_naloga {
            get {
                return ResourceManager.GetString("kreiranje_guest_naloga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiranje obaveštenja.
        /// </summary>
        public static string kreiranje_obavestenja {
            get {
                return ResourceManager.GetString("kreiranje_obavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string lozinka {
            get {
                return ResourceManager.GetString("lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuti.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi guest nalog.
        /// </summary>
        public static string napravi_guest_nalog {
            get {
                return ResourceManager.GetString("napravi_guest_nalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov.
        /// </summary>
        public static string naslov {
            get {
                return ResourceManager.GetString("naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBAVEŠTENJA.
        /// </summary>
        public static string obavestenja {
            get {
                return ResourceManager.GetString("obavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string obrisi {
            get {
                return ResourceManager.GetString("obrisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši nalog.
        /// </summary>
        public static string obrisi_nalog {
            get {
                return ResourceManager.GetString("obrisi_nalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik.
        /// </summary>
        public static string odaberite_jezik {
            get {
                return ResourceManager.GetString("odaberite_jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite režim.
        /// </summary>
        public static string odaberite_rezim {
            get {
                return ResourceManager.GetString("odaberite_rezim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odblokiraj pacijenta.
        /// </summary>
        public static string odblokiraj {
            get {
                return ResourceManager.GetString("odblokiraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string odustani {
            get {
                return ResourceManager.GetString("odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPCIJE.
        /// </summary>
        public static string opcije {
            get {
                return ResourceManager.GetString("opcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERACIJE.
        /// </summary>
        public static string operacije {
            get {
                return ResourceManager.GetString("operacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis povrede.
        /// </summary>
        public static string opis_povrede {
            get {
                return ResourceManager.GetString("opis_povrede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACIJENTI.
        /// </summary>
        public static string pacijenti {
            get {
                return ResourceManager.GetString("pacijenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite da napravite guest nalog?.
        /// </summary>
        public static string pitanje {
            get {
                return ResourceManager.GetString("pitanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak važenja godišnjeg.
        /// </summary>
        public static string pocetak_vazenja_godisnjeg {
            get {
                return ResourceManager.GetString("pocetak_vazenja_godisnjeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak važenja smene.
        /// </summary>
        public static string pocetak_vazenja_smene {
            get {
                return ResourceManager.GetString("pocetak_vazenja_smene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol.
        /// </summary>
        public static string pol {
            get {
                return ResourceManager.GetString("pol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTOJEĆI.
        /// </summary>
        public static string postojeci {
            get {
                return ResourceManager.GetString("postojeci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone.
        /// </summary>
        public static string postpone {
            get {
                return ResourceManager.GetString("postpone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string potvrdi {
            get {
                return ResourceManager.GetString("potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREGLEDI.
        /// </summary>
        public static string pregledi {
            get {
                return ResourceManager.GetString("pregledi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string prezime {
            get {
                return ResourceManager.GetString("prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži opcije.
        /// </summary>
        public static string prikazi_opcije {
            get {
                return ResourceManager.GetString("prikazi_opcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFIL.
        /// </summary>
        public static string profil {
            get {
                return ResourceManager.GetString("profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovanje pacijenta.
        /// </summary>
        public static string registrovanje_pacijenta {
            get {
                return ResourceManager.GetString("registrovanje-pacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string rs {
            get {
                return ResourceManager.GetString("rs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj.
        /// </summary>
        public static string sadrzaj {
            get {
                return ResourceManager.GetString("sadrzaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala.
        /// </summary>
        public static string sala {
            get {
                return ResourceManager.GetString("sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemsko ime.
        /// </summary>
        public static string sistemsko_ime {
            get {
                return ResourceManager.GetString("sistemsko_ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soba.
        /// </summary>
        public static string soba {
            get {
                return ResourceManager.GetString("soba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalizacija doktora.
        /// </summary>
        public static string specijalizacija {
            get {
                return ResourceManager.GetString("specijalizacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip korisnika.
        /// </summary>
        public static string tip_korisnika {
            get {
                return ResourceManager.GetString("tip_korisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje.
        /// </summary>
        public static string trajanje {
            get {
                return ResourceManager.GetString("trajanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme.
        /// </summary>
        public static string vreme {
            get {
                return ResourceManager.GetString("vreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAKAŽI HITAN PREGLED.
        /// </summary>
        public static string zakazi_hitan_pregled {
            get {
                return ResourceManager.GetString("zakazi_hitan_pregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAKAŽI HITNU OPERACIJU.
        /// </summary>
        public static string zakazi_hitnu_operaciju {
            get {
                return ResourceManager.GetString("zakazi_hitnu_operaciju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži pregled.
        /// </summary>
        public static string zakazi_pregled {
            get {
                return ResourceManager.GetString("zakazi_pregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazivanje hitnog pregleda.
        /// </summary>
        public static string zakazivanje_hitnog_pregleda {
            get {
                return ResourceManager.GetString("zakazivanje_hitnog_pregleda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazivanje operacije.
        /// </summary>
        public static string zakazivanje_operacije {
            get {
                return ResourceManager.GetString("zakazivanje_operacije", resourceCulture);
            }
        }
    }
}
